language: node_js
git:
  depth: 1
node_js:
  - "8"

cache:
  directories:
    - node_modules # NPM packages

services:
    - docker

install:
    - npm install --force

script:
    - npm run text
    - npm test
    - bash ./testSchema.sh
